import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

const pathNames = [
  "/inputs",
  "/data-display",
  "/feedback",
  "/surfaces",
  "/navigation",
  "/layout",
];

const links = [
  "Inputs",
  "Data-display",
  "Feedback",
  "Surfaces",
  "Navigation",
  "Layout",
];

export default function App({ Component, pageProps }: AppProps) {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Tailwind + mui</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="flex justify-evenly">
        {pathNames.map((path, i) => (
          <li key={path} className={path === router.asPath ? "active" : ""}>
            <Link href={path}>{links[i]}</Link>
          </li>
        ))}
      </nav>
      <Component {...pageProps} />
    </>
  );
}
